### ISSUE TITLE
errors in profile index.html, undefined method `major' for nil:NilClass

### ISSUE THREAD

**Issue by benkimo6i** [benkimo6i/profiles#5]
`
			
<div class="col-md-4">
	<p>
		<span class="glyphicon glyphicon-briefcase"></span>
		Previously a <b><%= p.experiences.last.title %></b> at <b><%= p.experiences.last.company %></b>
	</p>
</div>
			

<div class="col-md-4">
	<p>
		<span class="glyphicon glyphicon-education"></span>
		Degree in <b><%= p.educations.last.major %></b> at <b><%= p.educations.last.school %></b>
	</p>
</div>`

**Comment by 91juhwang** [comment]
Fixed it. 
I added if & else statements to check if the user updated their "education", "experience", and "skills" section.
